# Generated by Django 5.0.4 on 2026-03-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.TextField(verbose_name='Representação do objeto'),
        ),
    ]
